# Generated by Django 5.0.3 on 2024-03-20 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('username', models.CharField(max_length=30, unique=True)),
                ('password', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Story',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('headline', models.CharField(max_length=64)),
                ('category', models.CharField(choices=[('pol', 'Politics'), ('art', 'Art'), ('tech', 'Technology'), ('trivia', 'Trivial')], default='unknown', max_length=32)),
                ('region', models.CharField(choices=[('uk', 'UK News'), ('eu', 'European News'), ('w', 'World News')], default='unknown', max_length=32)),
                ('date', models.DateField()),
                ('details', models.CharField(max_length=128)),
                ('author', models.ManyToManyField(to='newsAggregator.author')),
            ],
        ),
    ]
